### PR TITLE
Render gh pages

### LINKED ISSUE #2: Improvements
- [ ] change the name to something more general
- [ ] update readme
- [ ] have a look at the `drake` package and possibly include it
- [ ] move all but the rendered files from gh_pages back to the master branch
- [ ] have another look at the Turing way book for more inspiration
- [x] add roxygen2 for documentation of functions and data
- [x] maybe include piggyback package to include large datasets in a package on Github

### PR DESCRIPTION
**Pull request by selinaZitrone**
**Render website to gh-pages branch**

I moved all files necessary for the website to the docs/ subdirectory on master.

The new Github action script render-gh-pages.yml renders the site on master if there were any changes to the docs/ subdirectory. Then it does a checkout to gh-pages, deletes the old website version and checks out the new website version from the master. 

Not sure if this is the best method to get the rendered files from master to gh-pages.
Also, I guess there should be some check for successful rendering of the website before the old version of the website gets deleted.
What do you think?

### CODE REVIEW

**Comment by selinaZitrone** [comment]
Something is not working in the Action. I will test it and reopen the PR later to avoid the R-cmd-check triggering everytime I test something

**Comment by selinaZitrone** [comment]
Now the Github Action render-gh-pages runs successfully and rendered results are pushed to the dummy branch gh-pages-test.
Before merging the test branches in the action have to be substituted by the actual branches:
render_gh_pages -> master
gh-pages-test -> gh-pages

**Comment by bitbacchus** [comment]
OK, I see why this feels awkward, but I don't see a more streamlined solution with a separate branch.

However, as an alternative, we could deploy to a /docs folder in the main branch and simply add this folder to the .gitignore. Why didn't we do this in the first place, again ;-)

But I would argue to simply merge the pull request because it works right now and its actually not worth the effort, IMHO.

**Comment by selinaZitrone** [comment]
Yes that would indeed have been an alternative. I think we even thought about it but in the end decided against it because the repo is also an R-package and should only contain things needed in the package.

I agree that we can merge like this. If we have time later, we can always change the structure and render to /docs.
Thanks for reviewing!

**Pull request merged**
